class: ml_project.models.regression.ExampleTF
params:
  input_fn_config:
    batch_size: 64
    num_epochs: 15
    shuffle: True
    queue_capacity: 1000
    num_threads: 1
  config:
    save_summary_steps: 1
    tf_random_seed: 42
    save_checkpoints_steps: 100
    #save_checkpoints_secs:
    keep_checkpoint_max: 5
    log_step_count_steps: 100
  params:
    learning_rate: 0.0001
    hooks:
      - type: SummarySaverHook
        params: {name: dense_layer_1_norm, op: scalar, save_steps: 10}
